// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

// Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

// Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';


// Sticky
export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE='NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS='FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS='UPDATE_ALL_NOTES_SUCCESS';

// Contact
export const GET_All_CONTACT_SUCCESS = 'GET_All_CONTACT_SUCCESS';
export const ON_ADD_CONTACT_SUCCESS = 'ON_ADD_CONTACT_SUCCESS';
export const UPDATE_CONTACT_SUCCESS='UPDATE_CONTACT_SUCCESS';
export const DELETE_CONTACT_SUCCESS='DELETE_CONTACT_SUCCESS';


// (1) SuperAdmin Panel Action Types
// ---------------------------------

// 1. Categories
export const  SUPER_ADMIN_GET_CATEGORIES = 'SUPER_ADMIN_GET_CATEGORIES';
export const  SUPER_ADMIN_RETRIEVE_CATEGORIES_SUCCESS = 'SUPER_ADMIN_RETRIEVE_CATEGORIES_SUCCESS';
export const  SUPER_ADMIN_RETRIEVE_CATEGORY_DETAILS_SUCCESS = 'SUPER_ADMIN_RETRIEVE_CATEGORY_DETAILS_SUCCESS';
export const  SUPER_ADMIN_CREATE_CATEGORY_SUCCESS = 'SUPER_ADMIN_CREATE_CATEGORY_SUCCESS';
export const  SUPER_ADMIN_UPDATE_CATEGORY_SUCCESS = 'SUPER_ADMIN_UPDATE_CATEGORY_SUCCESS';
export const  SUPER_ADMIN_DELETE_CATEGORY_SUCCESS = 'SUPER_ADMIN_DELETE_CATEGORY_SUCCESS';
export const  SUPER_ADMIN_ACTIVATE_CATEGORY_SUCCESS = 'SUPER_ADMIN_ACTIVATE_CATEGORY_SUCCESS';
export const  SUPER_ADMIN_DEACTIVATE_CATEGORY_SUCCESS = 'SUPER_ADMIN_DEACTIVATE_CATEGORY_SUCCESS';

// 2. Activities
export const  SUPER_ADMIN_RETRIEVE_ACTIVITIES_SUCCESS = 'SUPER_ADMIN_RETRIEVE_ACTIVITIES_SUCCESS';
export const  SUPER_ADMIN_RETRIEVE_ACTIVITY_DETAILS_SUCCESS = 'SUPER_ADMIN_RETRIEVE_ACTIVITY_DETAILS_SUCCESS';
export const  SUPER_ADMIN_CREATE_ACTIVITY_SUCCESS = 'SUPER_ADMIN_CREATE_ACTIVITY_SUCCESS';
export const  SUPER_ADMIN_UPDATE_ACTIVITY_SUCCESS = 'SUPER_ADMIN_UPDATE_ACTIVITY_SUCCESS';
export const  SUPER_ADMIN_DELETE_ACTIVITY_SUCCESS = 'SUPER_ADMIN_DELETE_ACTIVITY_SUCCESS';
export const  SUPER_ADMIN_ACTIVATE_ACTIVITY_SUCCESS = 'SUPER_ADMIN_ACTIVATE_ACTIVITY_SUCCESS';
export const  SUPER_ADMIN_DEACTIVATE_ACTIVITY_SUCCESS = 'SUPER_ADMIN_DEACTIVATE_ACTIVITY_SUCCESS';


// (2) iNauction - Web Console
// ---------------------------

// 1.Events

// 1.1 Host Part
export const HOST_RETRIEVE_EVENTS_SUCCESS = 'HOST_RETRIEVE_EVENTS_SUCCESS';
export const HOST_RETRIEVE_EVENT_DETAILS_SUCCESS = 'HOST_RETRIEVE_EVENT_DETAILS_SUCCESS';
export const HOST_CREATE_EVENT_SUCCESS = 'HOST_CREATE_EVENT_SUCCESS';
export const HOST_UPDATE_EVENT_SUCCESS = 'HOST_UPDATE_EVENT_SUCCESS';
export const HOST_PUBLISH_EVENT_SUCCESS = 'HOST_PUBLISH_EVENT_SUCCESS';
export const HOST_DELETE_EVENT_SUCCESS = 'HOST_DELETE_EVENT_SUCCESS';
export const HOST_CANCEL_EVENT_SUCCESS = 'HOST_CANCEL_EVENT_SUCCESS';

// 1.2. Bidder Part
export const BIDDER_ACCEPT_EVENT_INVITATION = 'BIDDER_ACCEPT_EVENT_INVITATION';
export const BIDDER_DECLINE_EVENT_INVITATION = 'BIDDER_DECLINE_EVENT_INVITATION';
export const BIDDER_ACCESS_OPENED_EVENT = 'BIDDER_ACCESS_OPENED_EVENT'; //-- Bidder can access an opened event if he want to participate in it--//
export const BIDDER_EXIT_OPENED_EVENT = 'BIDDER_EXIT_OPENED_EVENT'; //-- Bidder can exit a just event if he doesn't to further participate-//

// Errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';
