// Auth
export const GET_LOGIN = 'GET_LOGIN';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const ADD_USER = 'ADD_USER';
export const CLEAR_REGISTER = 'CLEAR_REGISTER';
export const RESEND_EMAIL = 'RESEND_EMAIL';
export const EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED';
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED';
// Experts
export const GET_EXPERTS = 'GET_EXPERTS';
export const ADD_EXPERT = 'ADD_EXPERT';
export const DELETE_EXPERT = 'DELETE_EXPERT';
export const GET_EXPERT = 'GET_EXPERT';
export const EXPERT_LOADING = 'EXPERT_LOADING';
export const UPDATE_EXPERT = 'UPDATE_EXPERT';
export const CLEAR_EXPERT = 'CLEAR_EXPERT';

// Errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

// Tasks
export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_TYPES = 'GET_TASKS_TYPES';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const GET_TASK = 'GET_TASK';
export const TASK_LOADING = 'TASK_LOADING';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAR_TASK = 'CLEAR_TASK';
export const GET_TASKS_EXPERT = 'GET_TASKS_EXPERT';
export const DELETE_TASK_EXPERT = 'DELETE_TASK_EXPERT';
export const ADD_TASK_TWO = 'ADD_TASK_TWO';
export const UPDATE_TASK_TWO = 'UPDATE_TASK_TWO';

// Bidders Invitations
export const SET_BIDDERS_LOADING = 'SET_BIDDERS_LOADING';
export const All_BIDDERS_RECEIVED = 'All_BIDDERS_RECEIVED';
export const CATEGORY_BIDDERS_RECEIVED = 'CATEGORY_BIDDERS_RECEIVED';
export const BIDDERS_INVITATIONS_RECEIVED = 'BIDDERS_INVITATIONS_RECEIVED';
export const INVITE_BIDDER = 'INVITE_BIDDER';
export const CLEAR_BIDDER_INVITATION = 'CLEAR_BIDDER_INVITATION';

// Company
export const ADD_COMPANY = 'ADD_COMPANY';
export const CLEAR_COMPANY = 'CLEAR_COMPANY';

// Events
export const GET_EVENTS = 'GET_EVENTS';
export const EVENTS_RECEIVED = 'EVENTS_RECEIVED';
export const DRAFT_EVENTS_RECEIVED = 'DRAFT_EVENTS_RECEIVED';
export const ADD_DRAFT_EVENT = 'ADD_DRAFT_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const CLEAR_EVENT = 'CLEAR_EVENT';

// Company Activities
export const GET_COMPANY_ACTIVITIES = 'GET_COMPANY_ACTIVITIES';
export const COMPANY_ACTIVITIES_RECEIVED = 'COMPANY_ACTIVITIES_RECEIVED';
export const COMPANY_ACTIVITIES_RESET_LOADING = 'COMPANY_ACTIVITIES_RESET_LOADING';

// System Activities
export const GET_SYSTEM_ACTIVITIES = 'GET_SYSTEM_ACTIVITIES';
export const SYSTEM_ACTIVITIES_RECEIVED = 'SYSTEM_ACTIVITIES_RECEIVED';

// Currencies
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const CURRENCIES_RECEIVED = 'CURRENCIES_RECEIVED';

// Company Registration Main Activities
export const GET_REGISTRATION_MAIN_ACTIVITIES = 'GET_REGISTRATION_MAIN_ACTIVITIES';

// Bidder Registration User Positions
export const GET_REGISTRATION_USER_POSITIONS = 'GET_REGISTRATION_USER_POSITIONS';

// Host Registration Form
export const HOST_REGISTRATION_FORM = 'HOST_REGISTRATION_FORM';

// Activities
export const ACT_CATEGORIES_RECEIVED = 'ACT_CATEGORIES_RECEIVED';
export const ACT_ACTIVITIES_RECEIVED = 'ACT_ACTIVITIES_RECEIVED';
export const ACT_COMPANY_ACTIVITIES_RECEIVED = 'ACT_COMPANY_ACTIVITIES_RECEIVED';
export const SET_LOADING = 'SET_LOADING';
export const RESET_LOADING = 'RESET_LOADING';

// App Notifications
export const APP_NOTIFICATIONS_RECEIVED = 'APP_NOTIFICATIONS_RECEIVED';
export const SET_APP_NOTIFICATIONS_LOADING = 'SET_APP_NOTIFICATIONS_LOADING';
export const RESET_APP_NOTIFICATIONS_LOADING = 'RESET_APP_NOTIFICATIONS_LOADING';