export const EVENTS_RECEIVED = 'EVENTS_RECEIVED';
export const DRAFT_EVENTS_RECEIVED = 'DRAFT_EVENTS_RECEIVED';
export const ADD_DRAFT_EVENT = 'ADD_DRAFT_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const CLEAR_EVENT = 'CLEAR_EVENT';
export const SET_LOADING = 'SET_LOADING';
export const RESET_LOADING = 'RESET_LOADING';
export const UOMS_RECEIVED = 'UOMS_RECEIVED';